"use client";

import { FormEvent, useState } from "react";

export function HomeContactForm() {
  const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setState("sending"); try { const response = await fetch("/api/inquiries/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), project: form.get("project"), message: form.get("message"), website: form.get("website") }) }); if (!response.ok) throw new Error("Request failed"); event.currentTarget.reset(); setState("success"); } catch { setState("error"); } }
  return <form className="contact-form" onSubmit={submit}><label className="form-honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off" /></label><label>Dein Name<input name="name" required minLength={2} placeholder="Wie heißt du?" /></label><label>E-Mail-Adresse<input name="email" type="email" required placeholder="name@unternehmen.de" /></label><label>Worum geht es?<select name="project" required defaultValue=""><option value="" disabled>Bitte auswählen</option><option>Website</option><option>Shopify-Shop</option><option>AI Automation</option><option>Anderes Projekt</option></select></label><label>Erzähl mir kurz davon<textarea name="message" required minLength={10} rows={4} placeholder="Was möchtest du umsetzen?" /></label>{state === "success" && <p className="contact-form-status" role="status">Danke, deine Anfrage wurde gespeichert. Ich melde mich zeitnah.</p>}{state === "error" && <p className="contact-form-status" role="alert">Die Anfrage konnte nicht gespeichert werden. Bitte versuche es erneut.</p>}<button className="contact-submit" type="submit" disabled={state === "sending"}>{state === "sending" ? "Wird gesendet..." : "Anfrage senden"} <span aria-hidden="true">↗</span></button><p>Oder schreibe mir direkt per WhatsApp oder E-Mail.</p></form>;
}
