export type ConceptProject = {
  slug: string;
  title: string;
  category: string;
  description: string;
  image: string;
  technologies: string[];
  challenge: string;
  approach: string;
};

export const concepts: ConceptProject[] = [
  { slug: "atelier-noir", title: "Atelier Noir", category: "Shopify · Fashion", description: "Editorial Commerce für eine reduzierte Fashion Brand mit klarer Produktführung.", image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1600&q=85", technologies: ["Shopify", "UX Design", "Editorial"], challenge: "Eine Kollektion soll hochwertig wirken, ohne den Kaufweg zu verstecken.", approach: "Eine ruhige Bildsprache, fokussierte Navigation und präzise Produktmomente schaffen Orientierung." },
  { slug: "solenne", title: "Solenne", category: "Shopify · Jewelry", description: "Eine Schmuckwelt, die feine Details, Materialität und Vertrauen in den Vordergrund stellt.", image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=1600&q=85", technologies: ["Shopify", "Art Direction", "Luxury"], challenge: "Wertigkeit muss digital unmittelbar spürbar werden.", approach: "Großzügige Räume, klare Beratungspunkte und ein konzentriertes Produkterlebnis bilden die Basis." },
  { slug: "aura-skin", title: "Aura Skin", category: "Shopify · Beauty", description: "Ein bewusster Beauty Store für Routinen, Inhaltsstoffe und wiederkehrende Käufe.", image: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1600&q=85", technologies: ["Shopify", "Brand Design", "DTC"], challenge: "Komplexe Produktinformationen sollen leicht verständlich bleiben.", approach: "Die Struktur verbindet ruhige Markenmomente mit klaren Ritualen und schnellen Entscheidungen." },
  { slug: "forma-living", title: "Forma Living", category: "Shopify · Furniture", description: "Ein Interior Store mit räumlicher Klarheit und warmer Materialität.", image: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1600&q=85", technologies: ["Shopify", "Interior", "UX Design"], challenge: "Möbel müssen im digitalen Raum Größe und Charakter behalten.", approach: "Kuratierte Szenen und eine übersichtliche Produktarchitektur geben den Stücken Raum." },
  { slug: "morning-works", title: "Morning Works", category: "Shopify · Coffee", description: "Eine Coffee Brand für Herkunft, Subscriptions und langsamere Morgen.", image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1600&q=85", technologies: ["Shopify", "Subscription", "Branding"], challenge: "Ein Produkt mit vielen Wiederkäufen braucht einen einfachen Einstieg.", approach: "Die Startseite führt von der Marke direkt in das passende Kaffee-Ritual." },
  { slug: "stride-studio", title: "Stride Studio", category: "Shopify · Sport", description: "Performance Commerce für technische Essentials und die nächste Trainingsrunde.", image: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1600&q=85", technologies: ["Shopify", "Performance", "DTC"], challenge: "Technische Produkte müssen schnell verständlich und begehrlich sein.", approach: "Klarer Nutzen, mutige Details und eine direkte Kaufstrecke halten das Erlebnis in Bewegung." },
  { slug: "field-notes", title: "Field Notes", category: "Shopify · Home goods", description: "Ein zurückhaltender Store für Objekte, die den Alltag bewusster begleiten.", image: "https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=1600&q=85", technologies: ["Shopify", "Lifestyle", "Art Direction"], challenge: "Kleine Alltagsprodukte brauchen eine starke Haltung statt lauter Werbung.", approach: "Die Gestaltung setzt auf Material, Nutzen und eine entschleunigte Erzählweise." },
  { slug: "casa-oro", title: "Casa Oro", category: "Shopify · Tableware", description: "Eine Tableware-Welt für Gastgeber, Rituale und großzügige Momente.", image: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&w=1600&q=85", technologies: ["Shopify", "Homeware", "Storytelling"], challenge: "Produkte für den Tisch sollen emotional und trotzdem konkret verkauft werden.", approach: "Warme Szenen und klare Sets führen von Inspiration zu einer einfachen Auswahl." },
  { slug: "northstar", title: "Northstar", category: "Firmenwebsite", description: "Eine Unternehmenswebsite für eine beratungsstarke Marke mit komplexem Angebot.", image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1600&q=85", technologies: ["Next.js", "Content Strategy", "SEO"], challenge: "Viele Leistungen müssen schnell verständlich und glaubwürdig präsentiert werden.", approach: "Eine prägnante Positionierung und klare Einstiegspunkte führen zu relevanten Gesprächen." },
  { slug: "orbital", title: "Orbital", category: "Landingpage", description: "Eine fokussierte SaaS-Landingpage für ein neues Produkt mit erklärungsbedürftigem Nutzen.", image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=85", technologies: ["Next.js", "Conversion", "Motion"], challenge: "Der Produktwert muss in Sekunden nachvollziehbar sein.", approach: "Eine klare Message-Hierarchie, starke Produktmomente und eine reduzierte Conversion-Strecke schaffen Fokus." },
  { slug: "signal-os", title: "Signal OS", category: "AI Automation", description: "Ein Konzept für KI-gestützte Workflows, die Anfragen priorisieren und Teams entlasten.", image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=85", technologies: ["OpenAI", "API", "Automation"], challenge: "Automatisierung muss nachvollziehbar bleiben und Vertrauen schaffen.", approach: "Ein transparentes Setup zeigt, was automatisiert wird, wann Menschen übernehmen und wo Zeit entsteht." },
  { slug: "frameboard", title: "Frameboard", category: "Dashboard", description: "Ein Analyse-Dashboard, das operative Kennzahlen in konkrete nächste Schritte übersetzt.", image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=85", technologies: ["Next.js", "Data UX", "Charts"], challenge: "Daten sollen Entscheidungen erleichtern statt neue Komplexität schaffen.", approach: "Ein ruhiges Interface priorisiert Trends, Ausnahmen und die jeweils nächste Handlung." },
  { slug: "relay-crm", title: "Relay CRM", category: "CRM", description: "Ein CRM-Konzept für einen klaren Überblick über Leads, Beziehungen und nächste Aufgaben.", image: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1600&q=85", technologies: ["React", "UX Systems", "Supabase"], challenge: "Teams brauchen Kontext, ohne sich durch Tabellen zu verlieren.", approach: "Die Oberfläche bringt Kontakte, Aktivitäten und Prioritäten in eine verständliche Arbeitsansicht." },
];

export function conceptBySlug(slug: string) {
  return concepts.find((concept) => concept.slug === slug);
}
